### PR TITLE
Add alternate style for table

### PR DESCRIPTION
**Pull request by PaulPowershell**
### Description
Add colored rows intermittently in tables with `.WithAlternateRowStyle(pterm.NewStyle(pterm.BgDarkGray))`

### Scope
table/alternate-row-style

- [ ] Bug Fix
- [X] New Feature
- [ ] Documentation
- [ ] Other

### Related Issue
Fixes https://github.com/pterm/pterm/issues/666

To-Do Checklist
- [X] tested my changes
- [X] have commented every method that I created/changed
- [X] updated the examples to fit with my changes
- [X] have added tests for my newly created methods

It's my first PR here, i don't know if i made all things correctly

### CODE REVIEW

**Comment by MarvinJWendt** [comment]
Thanks for the PR! 
Also thanks for fixing the linting, even tho the warnings were out of scope of your feature 💙

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for contributing 🚀

**Comment by PaulPowershell** [comment]
@MarvinJWendt i don't know if its in relation with my modifications or not but table in example have problems but not all, i havec check again all format table in local and it's ok, so i don't know..
https://github.com/pterm/pterm/tree/master/_examples/table

**Comment by MarvinJWendt** [comment]
I will look into it :)

**Pull request merged**
