### PR TITLE
feat: Add util functions to create tables from slices of structs

### PR DESCRIPTION
**Pull request by tw1nk**
### Description
Describe your work here.

This makes it easy to print a slice of structs. or a slice of pointers to structs

- [ ] Bug Fix
- [x] New Feature
- [ ] Documentation
- [ ] Other

### Related Issue
Fixes #

### To-Do Checklist
- [x] I tested my changes
- [x] I have commented every method that I created/changed
- [ ] I updated the examples to fit with my changes
- [x] I have added tests for my newly created methods

### CODE REVIEW

**Comment by MarvinJWendt** [comment]
Hi @tw1nk, thanks for the PR! I really like the feature. For such features, we have a dedicated package named `putils`. It contains utility function for PTerm, and we planned to include some methods for automatically filling tables via different input types (which your feature does). So if you could refactor your changes into the `putils` package (it's in the root of this repo) that would be awesome! Just create a new go file and name it  `table-from-struct-slice`, which contains two methods:

```go
TableFromStructSlice(tablePrinter, structSlice) pterm.TablePrinter // Accepts a customized table printer and adds data to it, then returns it.
DefaultTableFromStructSlice(tablePrinter, structSlice) pterm.TablePrinter // Uses the first method and feeds the default table printer into the first param and returns the table filled with your computed data.
```

**Comment by tw1nk** [comment]
Thanks will do. You already had a utility method WithCSVReader which was why I added it to the normal table printer.

Regarding the email.  thanks, i'll do that :D working from home and haven't setup my normal account on the work computer yet.

**Comment by MarvinJWendt** [comment]
Hi @tw1nk, I have refactored the PR a little, and tested it. I would merge it, but could you please change the filename real quick? It has a typo in "from". I will merge it then :)
Thanks for contributing 🚀 

And you don't need to update the `putils` readme, it will update itself, once it hits our CI-System :)

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for contributing :)

**Comment by MarvinJWendt** [comment]
Hi @tw1nk, the PR is now live in [`v0.12.23`](https://github.com/pterm/pterm/releases/tag/v0.12.23)

**Pull request merged**
