### PR TITLE
fix: Added possibility to correctly handle negative values for charts

### PR DESCRIPTION
**Pull request by anxp**
### Description
I've tried this great project for data visualization and found out that negative values are ignored while chart rendering. So I decided to add such feature. To provide best user experience, my chart canvas is adaptive - if chart has only positive values you will not see negative part of chart and vise versa. This way we effectively use available screen area. And only if data includes both negative and positive values, chart will be rendered form two parts - top (or right) for positive and bottom (or left) for negative.

### Scope
Barchart, examples for barchart, **and also I needed to update tests with new expected data**, because negative bars now actually displayed so they cannot pass current tests.

- [ ] Bug Fix
- [X] New Feature
- [ ] Documentation
- [ ] Other

### Related Issue
Fixes #

### To-Do Checklist
- [X] I tested my changes
- [X] I have commented every method that I created/changed
- [X] I updated the examples to fit with my changes
- [ ] I have added tests for my newly created methods _(I didn't create new methods, just actualized tests for current ones)_

### CODE REVIEW

**Comment by MarvinJWendt** [comment]
Hi @anxp, thanks for this amazing PR! There are some test cases missing, could you please add them?
If you need help with the tests just ping me 😄

**Comment by anxp** [comment]
> Hi @anxp, thanks for this amazing PR! There are some test cases missing, could you please add them? If you need help with the tests just ping me smile

Hi Marvin, yes, I've checked coverage and will add tests to cover all cases in new logic. I'll let you know when they will be ready :)

**Comment by anxp** [comment]
Hi, @MarvinJWendt ,
Pull request actualized:
1. More tests added to maximize coverage
2. Fixed a overlooked bug with displaying values for horizontal bar chart with both negative and positive values. On my initial version values was printed right after the bar, but now they aligned by right side (thanks to tests!) See attached pictures.

**My initial version**:
screenshot-017_1
**Now**:
screenshot-017_6

**Comment by anxp** [comment]
Just added snapshots with test data, which I accidentally forgot to include yesterday :)

**Comment by MarvinJWendt** [comment]
Looks good, but there is one thing I noticed:

According to your value positions on the horizontal barchart, it would make sense to include that in the vertical one too.

**Comment by anxp** [comment]
Hi, @MarvinJWendt , your remarks are quite appropriate, I'll do my best to fix these issues!

**Comment by anxp** [comment]
Hi, @MarvinJWendt, all done! Here are new screenshots for vertical and horizontal bar charts.
Also I beautified vertical alignment of values for horizontal bar chart.
**Was**:
```
5
10
-15
0
-20
```
**Now**:
```
 5
 10
-15
 0
-20
```
**Horizontal bars:**
screenshot-020_7
screenshot-020_6
screenshot-020_5

**Vertical bars:**
screenshot-020_4
screenshot-020_3
screenshot-020_2

**Review by MarvinJWendt — CHANGES_REQUESTED** [review]
Hi @anxp, sorry for the delay. I fixed the linting and regenerated the snapshots to make most of the CI pass. There is still a little coverage missing, could you include that in the tests?

(You can see the missing lines in the files tab, where Codecov commented)

Your updated examples are very good, but could you please extract them into separate examples, like `barchart-XXX`? The examples are used to auto generate the animations in the readme, and the barchart example won't fit into a single picture now 😅 

The rest of the code looks fine, so when the CI passes and the examples are split up, this PR is ready to merge. Thanks a lot for contributing.

**Comment by MarvinJWendt** [comment]
PS: I updated the repository settings, so the CI should always trigger without needing me to approve it, so you can directly see if it passes :)

**Comment by anxp** [comment]
Hi, @MarvinJWendt ,
I fixed coverage and added 3 example files for barchart - barchart_001, barchart_002, barchart_003. But I didn't delete original main.go one, because if I do so, I'll brake CI, because it will look for main.go file and won't find it. I think your help needed :)

**Comment by anxp** [comment]
Also there are something strange with TestTreePrinterNilPrint_* tests. Here on CI windows build fails, but on my linux machine it is far more interesting: 
test **works** if run it **directly** and **does not work if run it in package** with all tests -- see attached screenshot....
Kazam_screencast_00008

**Comment by anxp** [comment]
Hi, @MarvinJWendt , I've investigated how some tests runs in individual mode and in "in-package".

When we use this instruction:

`content,_ := printer.Srender()`

we predictably get the **same result** when running test **singly** and **in package** (with all tests).

But if we use this "trick" to capture what was supposed to go on the screen:

```
content := captureStdout(func(w io.Writer) {
	printer.Render()
})
```

we will get **two** different results.

For single test run output will be:

`"Hello, World!\n\n"`

And for in-package run:

`"\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n\r                                                                                \rHello, World!\n\n"`

Why we have such effect I don't even know :)

I fixed this behavior in this commit, please check:
[https://github.com/pterm/pterm/pull/305/commits/234039587832161efb6c3ed1ed295b17955a0a35](https://github.com/pterm/pterm/pull/305/commits/234039587832161efb6c3ed1ed295b17955a0a35)
but despite the fact that the fix works, I have not found real cause of the problem!

Terminology explanation (GoLand IDE):

screenshot-026_2

**Comment by anxp** [comment]
Hi, @MarvinJWendt, I made all the changes I wanted, branch is ready for review again :)

**Comment by MarvinJWendt** [comment]
Hi @anxp, I'll look at it now :)

**Comment by MarvinJWendt** [comment]
> I fixed coverage and added 3 example files for barchart - barchart_001, barchart_002, barchart_003. But I didn't delete original main.go one, because if I do so, I'll brake CI, because it will look for main.go file and won't find it. I think your help needed :)

Sorry, that was probably bad described from me. Adding examples is fairly easy, you can just create a new folder in `_examples` and create a `main.go` file in there. The CI will automatically render it and include the animation of it in the README then. I'll quickly do this for you.

To the tree printer problem. Yes that IS weird. I'll look into that, but for this PR your hotfix is fine :)

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for this awesome PR! I really appreciate your work. Sorry that it took me so long to review it, normally we get such things done in a couple of days, but school is very stressful at the moment. Anyway, I am glad that we can finally merge this now! I will create a new release today with the feature included. 🚀

**Pull request merged**
