### PR TITLE
feat(progressbar): add RemoveWhenDone

### LINKED ISSUE #11: Option to remove `Progressbar` when done
Add an option to remove `Progressbar` when done.

### PR DESCRIPTION
**Pull request by VictorAssunc**
### Description
Added option to remove Progress Bar when it's done.

- [ ] Bug Fix
- [X] New Feature
- [ ] Documentation
- [ ] Other

### Related Issue
Fixes #11 

### To-Do Checklist
- [X] I tested my changes
- [X] I have commented every method that I created/changed
- [ ] I updated the examples to fit with my changes
- [ ] I have added tests for my newly created methods

### CODE REVIEW

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for contributing! 🚀😄

**Comment by VictorAssunc** [comment]
> LGTM! Thanks for contributing! rocketsmile

Thanks for the opportunity! :smile:

**Comment by VictorAssunc** [comment]
Hello, could you add the `hacktoberfest-accepted` label to this PR? It appeared as invalid to me.
image

**Comment by MarvinJWendt** [comment]
Hi @VictorAssunc, I have added the `Hacktoberfest` label back to the repo for you. Could you please tell me if it worked? I would rather not create a new issue label, they are hard to get rid of 😅 I was not expecting that Hacktoberfest would mark PRs as invalid, because Hacktoberfest is over.
Sorry for the inconvenience. If that PR doesn't make it, feel free to write me and/or someone of the Hacktoberfest managers. You can link them here if it won't get approved.
Have a nice day 😄

**Comment by VictorAssunc** [comment]
Sorry, @MarvinJWendt, but it didn't work. :frowning_face:

**Comment by MarvinJWendt** [comment]
@VictorAssunc and now?

**Comment by MarvinJWendt** [comment]
If it still doesn't work, please email them about it: hacktoberfest@digitalocean.com
You can send them a link to this PR and tell them that your PR has been labeled invalid even though your PR has been accepted.

**Pull request merged**
