### PR TITLE
fix: use rune len

### LINKED ISSUE #684: Multiline Prefix length issue when using emojis
Use `len([]rune(p.Prefix.Text))` instead of `len(p.Prefix.Text)` in case of emojis

Current output:

```shell
✓  First Line
    Second line
```

Expected output:

```shell
✓  First Line
   Second line
```

### PR DESCRIPTION
**Pull request by franklinkim**
Fixes #684

### CODE REVIEW

**Review by MarvinJWendt — APPROVED** [review]
LGTM! Thanks for contributing 🚀

**Comment by franklinkim** [comment]
@MarvinJWendt thanks for merging. could you create a new release please

**Comment by MarvinJWendt** [comment]
Hi @franklinkim, sorry for the delay. I do have exams in a week, after that I should finally be able to work on PTerm again. There is currently a bug on the main branch, as it seems, so I would first have to take a look a that.

**Comment by MarvinJWendt** [comment]
Everything is fixed and a new release is published :)

**Pull request merged**
